runtime: python37

handlers:
  - url: /static
    static_dir: static

  - url: /favicon\.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon\.ico

  - url: /.*
    secure: always
    redirect_http_response_code: 307
    script: auto
